# Generated by Django 2.1.3 on 2018-11-18 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=264)),
                ('last_name', models.CharField(max_length=264)),
                ('email', models.EmailField(max_length=264, unique=True)),
                ('phone_number', models.IntegerField()),
                ('address', models.CharField(max_length=264)),
                ('city', models.CharField(max_length=264)),
                ('country', models.CharField(max_length=264)),
            ],
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rental_date', models.DateField()),
                ('return_date', models.DateField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='RentalRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_rate', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField()),
                ('real_cost', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='VehicleSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=264)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=264)),
            ],
        ),
        migrations.AddField(
            model_name='vehicle',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.VehicleSize'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_Type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.VehicleType'),
        ),
        migrations.AddField(
            model_name='rentalrate',
            name='vehicle_size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.VehicleSize'),
        ),
        migrations.AddField(
            model_name='rentalrate',
            name='vehicle_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.VehicleType'),
        ),
        migrations.AddField(
            model_name='rental',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.Vehicle'),
        ),
    ]
